name: bluetoothapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  velocity_x: ^3.6.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  firebase_auth: ^4.1.5
  firebase_core: ^2.4.0
  flutter_otp_text_field: ^1.1.1
  cloud_firestore: ^4.2.0
  getwidget: ^3.0.1
  mobile_scanner: ^2.1.0
  sizer: ^2.0.15
  flutter_profile_picture: ^2.0.0
  numeric_keyboard: ^1.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

