// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjspeNNaSItsx7SX6cjN26qAE-y2YepJE',
    appId: '1:319873343936:web:6a02bbf099f9703eb46825',
    messagingSenderId: '319873343936',
    projectId: 'digital-gas-monitoring-system',
    authDomain: 'digital-gas-monitoring-system.firebaseapp.com',
    databaseURL: 'https://digital-gas-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digital-gas-monitoring-system.appspot.com',
    measurementId: 'G-YNTKR3LXQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8HG0UABydRxBKiCxotbCRnM-ZvKG6Xg',
    appId: '1:319873343936:android:b36a27acfea0da3db46825',
    messagingSenderId: '319873343936',
    projectId: 'digital-gas-monitoring-system',
    databaseURL: 'https://digital-gas-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digital-gas-monitoring-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCOmtTYlIrBy6cK4GSTeO8T1TZ055Eujg',
    appId: '1:319873343936:ios:f08a9f52f6251b22b46825',
    messagingSenderId: '319873343936',
    projectId: 'digital-gas-monitoring-system',
    databaseURL: 'https://digital-gas-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digital-gas-monitoring-system.appspot.com',
    androidClientId: '319873343936-apc2ba5n714qha1e0n4gtg20gdem1mpf.apps.googleusercontent.com',
    iosClientId: '319873343936-1vb7a6r3chdq8126mn90o75nl0u2n4gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetoothapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCOmtTYlIrBy6cK4GSTeO8T1TZ055Eujg',
    appId: '1:319873343936:ios:f08a9f52f6251b22b46825',
    messagingSenderId: '319873343936',
    projectId: 'digital-gas-monitoring-system',
    databaseURL: 'https://digital-gas-monitoring-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'digital-gas-monitoring-system.appspot.com',
    androidClientId: '319873343936-apc2ba5n714qha1e0n4gtg20gdem1mpf.apps.googleusercontent.com',
    iosClientId: '319873343936-1vb7a6r3chdq8126mn90o75nl0u2n4gr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluetoothapp',
  );
}
